### ISSUE TITLE
Crashes on Mac with M1

### ISSUE THREAD

**Issue by domschl** [denglerchr/Mosquitto.jl#2]
Thanks for picking up MQTT!

My environment:
Mosquitto 2.0.10_1 arm64 version installed via homebrew
macOS 12.0.1, arm64
Julia 1.8 built from master

Note: it works correctly with Linux (Intel) but also fails on macOS 12, Intel, with Julia 1.6
```
julia> using Mosquitto
Internal error: encountered unexpected error during compilation of __init__:
TypeError(func=:ccall, context="", expected=Symbol, got=nothing)
ijl_type_error_rt at /Users/dsc/gith/julia/src/rtutils.c:119
ijl_type_error at /Users/dsc/gith/julia/src/rtutils.c:127
interpret_symbol_arg at /Users/dsc/gith/julia/src/./ccall.cpp:0
emit_ccall at /Users/dsc/gith/julia/src/./ccall.cpp:1262
emit_expr at /Users/dsc/gith/julia/src/codegen.cpp:4597
emit_ssaval_assign at /Users/dsc/gith/julia/src/codegen.cpp:4229
emit_stmtpos at /Users/dsc/gith/julia/src/codegen.cpp:0 [inlined]
emit_function at /Users/dsc/gith/julia/src/codegen.cpp:7316
jl_emit_code at /Users/dsc/gith/julia/src/codegen.cpp:7678
jl_emit_codeinst at /Users/dsc/gith/julia/src/codegen.cpp:7723
_jl_compile_codeinst at /Users/dsc/gith/julia/src/jitlayers.cpp:110
jl_generate_fptr_impl at /Users/dsc/gith/julia/src/jitlayers.cpp:336
jl_compile_method_internal at /Users/dsc/gith/julia/src/gf.c:1982
_jl_invoke at /Users/dsc/gith/julia/src/gf.c:2247 [inlined]
ijl_apply_generic at /Users/dsc/gith/julia/src/gf.c:2437
jl_apply at /Users/dsc/gith/julia/src/./julia.h:1782 [inlined]
jl_module_run_initializer at /Users/dsc/gith/julia/src/toplevel.c:73
ijl_init_restored_modules at /Users/dsc/gith/julia/src/dump.c:2241
_include_from_serialized at ./loading.jl:768
_require_search_from_serialized at ./loading.jl:858
_require_search_from_serialized at ./loading.jl:831 [inlined]
_require at ./loading.jl:1118
require at ./loading.jl:1034
require at ./loading.jl:1018
_jl_invoke at /Users/dsc/gith/julia/src/gf.c:0 [inlined]
ijl_apply_generic at /Users/dsc/gith/julia/src/gf.c:2437
jl_apply at /Users/dsc/gith/julia/src/./julia.h:1782 [inlined]
call_require at /Users/dsc/gith/julia/src/toplevel.c:429 [inlined]
eval_import_path at /Users/dsc/gith/julia/src/toplevel.c:466
jl_toplevel_eval_flex at /Users/dsc/gith/julia/src/toplevel.c:692
jl_toplevel_eval_flex at /Users/dsc/gith/julia/src/toplevel.c:833
ijl_toplevel_eval at /Users/dsc/gith/julia/src/toplevel.c:898 [inlined]
ijl_toplevel_eval_in at /Users/dsc/gith/julia/src/toplevel.c:948
eval at ./boot.jl:368 [inlined]
eval_user_input at /Users/dsc/gith/julia/usr/share/julia/stdlib/v1.8/REPL/src/REPL.jl:151
repl_backend_loop at /Users/dsc/gith/julia/usr/share/julia/stdlib/v1.8/REPL/src/REPL.jl:245
start_repl_backend at /Users/dsc/gith/julia/usr/share/julia/stdlib/v1.8/REPL/src/REPL.jl:230
#run_repl#47 at /Users/dsc/gith/julia/usr/share/julia/stdlib/v1.8/REPL/src/REPL.jl:363
run_repl at /Users/dsc/gith/julia/usr/share/julia/stdlib/v1.8/REPL/src/REPL.jl:350
_jl_invoke at /Users/dsc/gith/julia/src/gf.c:0 [inlined]
ijl_apply_generic at /Users/dsc/gith/julia/src/gf.c:2437
#938 at ./client.jl:394
jfptr_YY.938_26308 at /Users/dsc/gith/julia/usr/lib/julia/sys.dylib (unknown line)
_jl_invoke at /Users/dsc/gith/julia/src/gf.c:0 [inlined]
ijl_apply_generic at /Users/dsc/gith/julia/src/gf.c:2437
jl_apply at /Users/dsc/gith/julia/src/./julia.h:1782 [inlined]
jl_f__call_latest at /Users/dsc/gith/julia/src/builtins.c:757
#invokelatest#2 at ./essentials.jl:718 [inlined]
invokelatest at ./essentials.jl:716 [inlined]
run_main_repl at ./client.jl:379
exec_options at ./client.jl:309
_start at ./client.jl:497
jfptr__start_38633 at /Users/dsc/gith/julia/usr/lib/julia/sys.dylib (unknown line)
_jl_invoke at /Users/dsc/gith/julia/src/gf.c:0 [inlined]
ijl_apply_generic at /Users/dsc/gith/julia/src/gf.c:2437
jl_apply at /Users/dsc/gith/julia/src/./julia.h:1782 [inlined]
true_main at /Users/dsc/gith/julia/src/jlapi.c:562
jl_repl_entrypoint at /Users/dsc/gith/julia/src/jlapi.c:706
Internal error: encountered unexpected error during compilation of __init__:
TypeError(func=:ccall, context="", expected=Symbol, got=nothing)
ijl_type_error_rt at /Users/dsc/gith/julia/src/rtutils.c:119
ijl_type_error at /Users/dsc/gith/julia/src/rtutils.c:127
interpret_symbol_arg at /Users/dsc/gith/julia/src/./ccall.cpp:0
emit_ccall at /Users/dsc/gith/julia/src/./ccall.cpp:1262
emit_expr at /Users/dsc/gith/julia/src/codegen.cpp:4597
emit_assignment at /Users/dsc/gith/julia/src/codegen.cpp:4331 [inlined]
emit_expr at /Users/dsc/gith/julia/src/codegen.cpp:4606
emit_ssaval_assign at /Users/dsc/gith/julia/src/codegen.cpp:4229
emit_stmtpos at /Users/dsc/gith/julia/src/codegen.cpp:0 [inlined]
emit_function at /Users/dsc/gith/julia/src/codegen.cpp:7316
jl_emit_code at /Users/dsc/gith/julia/src/codegen.cpp:7678
jl_emit_codeinst at /Users/dsc/gith/julia/src/codegen.cpp:7723
_jl_compile_codeinst at /Users/dsc/gith/julia/src/jitlayers.cpp:110
jl_generate_fptr_for_unspecialized_impl at /Users/dsc/gith/julia/src/jitlayers.cpp:380
jl_compile_method_internal at /Users/dsc/gith/julia/src/gf.c:1988
_jl_invoke at /Users/dsc/gith/julia/src/gf.c:2247 [inlined]
ijl_apply_generic at /Users/dsc/gith/julia/src/gf.c:2437
jl_apply at /Users/dsc/gith/julia/src/./julia.h:1782 [inlined]
jl_module_run_initializer at /Users/dsc/gith/julia/src/toplevel.c:73
ijl_init_restored_modules at /Users/dsc/gith/julia/src/dump.c:2241
_include_from_serialized at ./loading.jl:768
_require_search_from_serialized at ./loading.jl:858
_require_search_from_serialized at ./loading.jl:831 [inlined]
_require at ./loading.jl:1118
require at ./loading.jl:1034
require at ./loading.jl:1018
_jl_invoke at /Users/dsc/gith/julia/src/gf.c:0 [inlined]
ijl_apply_generic at /Users/dsc/gith/julia/src/gf.c:2437
jl_apply at /Users/dsc/gith/julia/src/./julia.h:1782 [inlined]
call_require at /Users/dsc/gith/julia/src/toplevel.c:429 [inlined]
eval_import_path at /Users/dsc/gith/julia/src/toplevel.c:466
jl_toplevel_eval_flex at /Users/dsc/gith/julia/src/toplevel.c:692
jl_toplevel_eval_flex at /Users/dsc/gith/julia/src/toplevel.c:833
ijl_toplevel_eval at /Users/dsc/gith/julia/src/toplevel.c:898 [inlined]
ijl_toplevel_eval_in at /Users/dsc/gith/julia/src/toplevel.c:948
eval at ./boot.jl:368 [inlined]
eval_user_input at /Users/dsc/gith/julia/usr/share/julia/stdlib/v1.8/REPL/src/REPL.jl:151
repl_backend_loop at /Users/dsc/gith/julia/usr/share/julia/stdlib/v1.8/REPL/src/REPL.jl:245
start_repl_backend at /Users/dsc/gith/julia/usr/share/julia/stdlib/v1.8/REPL/src/REPL.jl:230
#run_repl#47 at /Users/dsc/gith/julia/usr/share/julia/stdlib/v1.8/REPL/src/REPL.jl:363
run_repl at /Users/dsc/gith/julia/usr/share/julia/stdlib/v1.8/REPL/src/REPL.jl:350
_jl_invoke at /Users/dsc/gith/julia/src/gf.c:0 [inlined]
ijl_apply_generic at /Users/dsc/gith/julia/src/gf.c:2437
#938 at ./client.jl:394
jfptr_YY.938_26308 at /Users/dsc/gith/julia/usr/lib/julia/sys.dylib (unknown line)
_jl_invoke at /Users/dsc/gith/julia/src/gf.c:0 [inlined]
ijl_apply_generic at /Users/dsc/gith/julia/src/gf.c:2437
jl_apply at /Users/dsc/gith/julia/src/./julia.h:1782 [inlined]
jl_f__call_latest at /Users/dsc/gith/julia/src/builtins.c:757
#invokelatest#2 at ./essentials.jl:718 [inlined]
invokelatest at ./essentials.jl:716 [inlined]
run_main_repl at ./client.jl:379
exec_options at ./client.jl:309
_start at ./client.jl:497
jfptr__start_38633 at /Users/dsc/gith/julia/usr/lib/julia/sys.dylib (unknown line)
_jl_invoke at /Users/dsc/gith/julia/src/gf.c:0 [inlined]
ijl_apply_generic at /Users/dsc/gith/julia/src/gf.c:2437
jl_apply at /Users/dsc/gith/julia/src/./julia.h:1782 [inlined]
true_main at /Users/dsc/gith/julia/src/jlapi.c:562
jl_repl_entrypoint at /Users/dsc/gith/julia/src/jlapi.c:706
ERROR: InitError: `ccall` requires the compiler
Stacktrace:
 [1] __init__()
   @ Mosquitto ~/.julia/packages/Mosquitto/RLnD9/src/Mosquitto.jl:18
 [2] _include_from_serialized(path::String, depmods::Vector{Any})
   @ Base ./loading.jl:768
 [3] _require_search_from_serialized(pkg::Base.PkgId, sourcepath::String, depth::Int64)
   @ Base ./loading.jl:858
 [4] _require_search_from_serialized
   @ ./loading.jl:831 [inlined]
 [5] _require(pkg::Base.PkgId)
   @ Base ./loading.jl:1118
 [6] require(uuidkey::Base.PkgId)
   @ Base ./loading.jl:1034
 [7] require(into::Module, mod::Symbol)
   @ Base ./loading.jl:1018
during initialization of module Mosquitto
```

**Comment by denglerchr** [comment]
I forgot to search for the lib on Mac, possibly fixed now with https://github.com/denglerchr/Mosquitto.jl/commit/4378cd187dc90c49fc9026cb80d7c5fdb8c4977c but I don't have a Mac myself to test.
If you could ]update in julia and either comment here again of close the issue if it works now, would be appreciated.

**Comment by domschl** [comment]
It works now on Intel Macs with Julia 1.6, however I am still having problems with M1 Mac:

```
julia> using Mosquitto
ERROR: InitError: "Could not find the mosquitto library. If you're sure that it's installed, 
try adding it to DL_LOAD_PATH and rebuild the package."
Stacktrace:
 [1] __init__()
   @ Mosquitto ~/.julia/packages/Mosquitto/6uNWT/src/Mosquitto.jl:17
 [2] _include_from_serialized(path::String, depmods::Vector{Any})
   @ Base ./loading.jl:768
 [3] _require_search_from_serialized(pkg::Base.PkgId, sourcepath::String, depth::Int64)
   @ Base ./loading.jl:858
 [4] _require_search_from_serialized
   @ ./loading.jl:831 [inlined]
 [5] _require(pkg::Base.PkgId)
   @ Base ./loading.jl:1118
 [6] require(uuidkey::Base.PkgId)
   @ Base ./loading.jl:1034
 [7] require(into::Module, mod::Symbol)
   @ Base ./loading.jl:1018
during initialization of module Mosquitto
```
I've tried to set `DL_LOAD_PATH=/opt/homebrew/lib` (the location of the lib), rebuild, but that didn't help.

**Comment by domschl** [comment]
Ok, this can be solved by starting julia with additional library-load-path:
```
DYLD_LIBRARY_PATH=/opt/homebrew/lib julia
```
Then it all works with M1. Thank you!
